/* Rhoodstone Mission v4 — real Supabase admin CRUD */
const C=window.RHOOD_CONFIG||{};
const {createClient}=window.supabase||{};
const sb=(createClient&&C.SUPABASE_URL&&C.SUPABASE_ANON_KEY&&!C.SUPABASE_URL.includes('YOUR_'))?createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let selected=null,tasks=[];
function msg(t,bad=false){$('formMsg').textContent=t;$('formMsg').className='form-msg '+(bad?'bad':'')}
async function requireAdmin(){if(!sb)return false;const {data:{session}}=await sb.auth.getSession();if(!session)return false;const {data}=await sb.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();return !!data}
async function boot(){if(!sb){$('auth').classList.remove('hidden');$('console').classList.add('hidden');return}const ok=await requireAdmin();if(!ok){$('auth').classList.remove('hidden');$('console').classList.add('hidden');return}$('auth').classList.add('hidden');$('console').classList.remove('hidden');await loadProjects()}
$('loginForm').onsubmit=async e=>{e.preventDefault();if(!sb)return msg('Add Supabase URL and anon key in config.js.',true);const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return msg(error.message,true);location.reload()};
$('logout').onclick=async()=>{if(sb)await sb.auth.signOut();location.reload()};
async function loadProjects(){const {data,error}=await sb.from('projects').select('*').order('starts_at',{ascending:false});if(error)return msg(error.message,true);window.projects=data||[];renderRows()}
function renderRows(){$('rows').innerHTML=(window.projects||[]).map((p,i)=>`<div class="tr"><span><b>${esc(p.name)}</b><small>${esc(p.slug)}</small></span><span>${new Date(p.starts_at).toLocaleString()}<br>→ ${new Date(p.ends_at).toLocaleString()}</span><span>${p.gtd_slots}</span><span>${p.status}</span><span><button class="btn outline" onclick="edit(${i})">Edit</button></span></div>`).join('')||'<div class="empty">No campaigns yet.</div>'}
window.edit=async i=>{selected=window.projects[i];$('pName').value=selected.name;$('pSlug').value=selected.slug;$('pDesc').value=selected.description||'';$('pStart').value=toLocal(selected.starts_at);$('pEnd').value=toLocal(selected.ends_at);$('pGtd').value=selected.gtd_slots;$('pLogo').value=selected.logo_url||'';const {data,error}=await sb.from('mission_tasks').select('*').eq('project_id',selected.id).order('sort_order');if(error)return msg(error.message,true);tasks=data||[];renderTaskEditor();$('saveProject').textContent='Save Campaign'};
function toLocal(v){const d=new Date(v);const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function renderTaskEditor(){if(!selected){$('taskEditor').innerHTML='<p class="muted">Create a campaign first, then add tasks.</p>';return}$('taskCount').textContent=tasks.length;$('taskEditor').innerHTML=`<div class="selected">Editing: <b>${esc(selected.name)}</b></div>${tasks.map((t,i)=>`<div class="admin-task"><span>${String(i+1).padStart(2,'0')}</span><input value="${esc(t.title)}" onchange="tasks[${i}].title=this.value"><select onchange="tasks[${i}].task_type=this.value"><option value="x_follow" ${t.task_type==='x_follow'?'selected':''}>x_follow</option><option value="x_like" ${t.task_type==='x_like'?'selected':''}>x_like</option><option value="x_repost" ${t.task_type==='x_repost'?'selected':''}>x_repost</option><option value="website" ${t.task_type==='website'?'selected':''}>website</option><option value="discord" ${t.task_type==='discord'?'selected':''}>discord</option><option value="custom" ${t.task_type==='custom'?'selected':''}>custom</option></select><input placeholder="Target URL / ID" value="${esc(t.target_value||'')}" onchange="tasks[${i}].target_value=this.value"><button class="btn danger" onclick="tasks.splice(${i},1);renderTaskEditor()">Remove</button></div>`).join('')}<div class="task-add"><input id="newTask" placeholder="Task title"><select id="newType"><option value="x_follow">x_follow</option><option value="x_like">x_like</option><option value="x_repost">x_repost</option><option value="website">website</option><option value="discord">discord</option><option value="custom">custom</option></select><input id="newTarget" placeholder="Target URL / ID"><button class="btn outline" onclick="addTask()">Add task</button></div><button class="btn primary" onclick="saveTasks()">Save tasks</button>`}
window.addTask=()=>{const v=$('newTask').value.trim();if(!v)return;tasks.push({title:v,task_type:$('newType').value,target_value:$('newTarget').value.trim(),required:true,sort_order:tasks.length});renderTaskEditor()};
window.saveTasks=async()=>{if(!selected)return;await sb.from('mission_tasks').delete().eq('project_id',selected.id);const {error}=await sb.from('mission_tasks').insert(tasks.map((t,i)=>({project_id:selected.id,title:t.title,task_type:t.task_type,target_value:t.target_value||null,required:t.required!==false,sort_order:i})));if(error)return msg(error.message,true);msg('Tasks saved.');await loadProjects()};
$('projectForm').onsubmit=async e=>{e.preventDefault();if(!sb)return msg('Configure Supabase first.',true);const start=new Date($('pStart').value),end=new Date($('pEnd').value);if(end-start!==86400000)return msg('Campaign must be exactly 24 hours.',true);const row={name:$('pName').value.trim(),slug:$('pSlug').value.trim(),description:$('pDesc').value.trim(),starts_at:start.toISOString(),ends_at:end.toISOString(),gtd_slots:Number($('pGtd').value),logo_url:$('pLogo').value.trim()||null,status:'scheduled'};let res;if(selected)res=await sb.from('projects').update(row).eq('id',selected.id).select().single();else res=await sb.from('projects').insert(row).select().single();if(res.error)return msg(res.error.message,true);selected=res.data;tasks=[];renderTaskEditor();msg(selected?'Campaign saved.':'Campaign created.');await loadProjects()};
$('newCampaign').onclick=()=>{selected=null;tasks=[];$('projectForm').reset();$('pGtd').value=15;$('saveProject').textContent='Create Campaign';renderTaskEditor()};$('refresh').onclick=loadProjects;boot();
