const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const CHAIN_ID = 4663;
const CHAIN_HEX = '0x1237';
let assets = [], selected = null, wallet = null;

function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function short(a){return a ? `${a.slice(0,6)}…${a.slice(-4)}` : '—';}
function toast(msg, good=true){const t=$('#toast');t.textContent=msg;t.className=`toast show ${good?'':'bad'}`;clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),3200);}
async function api(url,opt={}){const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;}

$('#boot').innerHTML=['BOOT // Robinhood Chain Copilot','RPC // reading mainnet state','CHAIN // 4663 configured','DATA // loading Stock Token registry','MODE // non-custodial intelligence','READY // terminal online'].map(x=>`<p>> ${x}</p>`).join('');

async function health(){try{const d=await api('/api/health');$('#block').textContent=Number(d.block).toLocaleString();$('#gas').textContent=d.gasPrice?`${(Number(d.gasPrice)/1e9).toFixed(2)} gwei`:'—';$('#health').textContent='ONLINE';$('#health').className='good';$('#systemStatus').textContent='● ONLINE';}catch(e){$('#health').textContent='OFFLINE';$('#health').className='bad-text';$('#systemStatus').textContent='● DEGRADED';}}
health();setInterval(health,15000);

async function loadAssets(){try{const d=await api('/api/stock/assets');const all=Array.isArray(d)?d:(d.assets||[]);assets=all.filter(a=>(a.deployments||[]).some(x=>Number(x.chainId)===CHAIN_ID));renderStocks(filterStocks());if(assets.length){$('#ticker').innerHTML=[...assets.slice(0,35),...assets.slice(0,35)].map(a=>`<span>${escapeHtml(a.tokenSymbol||'TOKEN')} ◆ ${escapeHtml(a.tokenName||'')}</span>`).join('');}else $('#ticker').textContent='NO STOCK TOKENS RETURNED';}catch(e){$('#stockList').innerHTML=`<div class="empty">STOCK TOKEN API UNAVAILABLE<br><small>${escapeHtml(e.message)}</small></div>`;$('#ticker').textContent='MARKET DATA UNAVAILABLE';}}
function filterStocks(){const q=$('#stockSearch').value.trim().toLowerCase();return assets.filter(a=>!q||String(a.tokenSymbol||'').toLowerCase().includes(q)||String(a.tokenName||'').toLowerCase().includes(q)).slice(0,150)}
function renderStocks(list){if(!list.length){$('#stockList').innerHTML='<div class="empty">NO MATCHING TOKENS.</div>';return}$('#stockList').innerHTML=list.map(a=>`<button class="stock-row ${selected?.tokenSymbol===a.tokenSymbol?'active':''}" data-symbol="${escapeHtml(a.tokenSymbol)}"><span class="coin">${escapeHtml((a.tokenSymbol||'??').slice(0,2))}</span><span><b>${escapeHtml(a.tokenSymbol||'—')}</b><small>${escapeHtml(a.tokenName||'')}</small></span><strong>LIVE</strong></button>`).join('');$$('.stock-row').forEach(b=>b.onclick=()=>showStock(assets.find(a=>a.tokenSymbol===b.dataset.symbol)));}
async function showStock(a){if(!a)return;selected=a;renderStocks(filterStocks());const dep=(a.deployments||[]).find(x=>Number(x.chainId)===CHAIN_ID);let q=null;try{const d=await api('/api/stock/prices/'+encodeURIComponent(a.tokenSymbol));q=(d.quotes||[])[0]||d;}catch{}const money=v=>v==null||v===''?'—':`$${Number(v).toLocaleString(undefined,{maximumFractionDigits:6})}`;$('#stockDetail').innerHTML=`<div class="eyebrow">STOCK TOKEN // CHAIN ${CHAIN_ID}</div><h3 class="asset-title">${escapeHtml(a.tokenSymbol)} <small>${escapeHtml(a.tokenName||'')}</small></h3><div class="quote">${money(q?.ask||q?.price)}</div><div class="detail-grid">${[['BID',money(q?.bid)],['ASK',money(q?.ask)],['DAILY VOLUME',q?.dailyTradingVolume?Number(q.dailyTradingVolume).toLocaleString():'—'],['TRADING HALT',q?.isTradingHalt===true?'YES':q?.isTradingHalt===false?'NO':'—'],['MULTIPLIER',a.currentMultiplier||'—'],['CONTRACT',dep?.contractAddress?`<a target="_blank" rel="noopener" href="https://robinhoodchain.blockscout.com/address/${encodeURIComponent(dep.contractAddress)}">${short(dep.contractAddress)} ↗</a>`:'—']].map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join('')}</div>`;}
$('#stockSearch').oninput=()=>renderStocks(filterStocks());$('#clearStock').onclick=()=>{$('#stockSearch').value='';renderStocks(filterStocks());$('#stockSearch').focus()};loadAssets();

async function connectWallet(){if(!window.ethereum){toast('No EVM wallet detected. Install a compatible wallet.',false);return}try{try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:CHAIN_HEX}]})}catch(e){if(e.code===4902)await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:CHAIN_HEX,chainName:'Robinhood Chain',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://rpc.mainnet.chain.robinhood.com'],blockExplorerUrls:['https://robinhoodchain.blockscout.com/']}]});else throw e;}const a=await window.ethereum.request({method:'eth_requestAccounts'});wallet=a[0];$('#connect').textContent=short(wallet);$('#walletAddr').textContent=wallet;await loadWallet();toast('Wallet connected.');}catch(e){toast(e.message,false)}}
$('#connect').onclick=connectWallet;
async function loadWallet(){if(!wallet){toast('Connect a wallet first.',false);return}try{const d=await api('/api/wallet/'+wallet);$('#totalValue').textContent=`${Number(d.eth).toFixed(6)} ETH`;$('#portfolioNote').textContent='LIVE NATIVE BALANCE · READ ONLY';let html=`<div class="rows"><div><span>ETH</span><b>${Number(d.eth).toFixed(6)}</b></div><div><span>INDEXED DATA</span><b>${d.indexed?'AVAILABLE':'NOT CONFIGURED'}</b></div></div>`;if(d.indexed?.tokens?.length)html+=`<div class="muted asset-note">${d.indexed.tokens.length} indexed token records available.</div>`;else html+=`<div class="muted asset-note">Set ALCHEMY_API_KEY on the server for indexed token/transaction data.</div>`;$('#assetMini').innerHTML=html;}catch(e){toast(e.message,false)}}$('#refreshWallet').onclick=loadWallet;
if(window.ethereum)window.ethereum.on?.('accountsChanged',a=>{if(!a.length){wallet=null;$('#connect').textContent='Connect Wallet';$('#walletAddr').textContent='WALLET NOT CONNECTED';$('#totalValue').textContent='— ETH';$('#assetMini').innerHTML='<div class="empty">No wallet connected.</div>'}else{wallet=a[0];$('#connect').textContent=short(wallet);$('#walletAddr').textContent=wallet;loadWallet()}});

async function scan(){const a=$('#scanInput').value.trim();if(!a){toast('Enter an address first.',false);return}$('#scanResult').innerHTML='<div class="loading">SCANNING MAINNET…</div>';try{const d=await api('/api/address/'+encodeURIComponent(a));const risk=d.type==='CONTRACT'?'REVIEW REQUIRED':'LOW CONCERN';$('#scanResult').innerHTML=`<div class="eyebrow">READ-ONLY TECHNICAL INSPECTION</div><div class="risk">${risk}</div><div class="scan-grid">${[['TYPE',d.type],['ETH BALANCE',`${Number(d.ethBalance).toFixed(8)} ETH`],['NONCE',d.nonce],['BYTECODE',`${d.bytecodeBytes} bytes`],['ADDRESS',short(d.address)],['CHAIN',CHAIN_ID]].map(x=>`<div><span>${x[0]}</span><b>${escapeHtml(x[1])}</b></div>`).join('')}</div><a class="btn" target="_blank" rel="noopener" href="${d.blockscout}">Open Blockscout ↗</a>`;location.hash='scanner';}catch(e){$('#scanResult').innerHTML=`<div class="empty bad-text">SCAN FAILED<br>${escapeHtml(e.message)}</div>`}}
$('#scan').onclick=scan;$('#scanInput').onkeydown=e=>{if(e.key==='Enter')scan()};$('#paste').onclick=async()=>{try{$('#scanInput').value=await navigator.clipboard.readText();toast('Address pasted.')}catch{toast('Clipboard permission unavailable.',false)}};$('#heroScan').onclick=()=>{$('#scanInput').focus();location.hash='scanner'};

async function loadBridge(){try{const d=await api('/api/bridge-info');$('#bridgeGrid').innerHTML=d.routes.map(r=>`<article class="card feature"><div class="eyebrow">DOCUMENTED ROUTE</div><h3>${escapeHtml(r.name)}</h3><div class="speed">${escapeHtml(r.speed)}</div><p>${escapeHtml(r.bestFor)}</p><span class="tag">${r.official?'OFFICIAL DOC ROUTE':'REFERENCE'}</span></article>`).join('')+`<div class="notice full">${escapeHtml(d.note)}</div>`;}catch(e){$('#bridgeGrid').innerHTML=`<div class="empty">${escapeHtml(e.message)}</div>`}}$('#refreshBridge').onclick=loadBridge;loadBridge();

async function loadProjects(){try{const rows=await api('/api/projects');$('#projects').innerHTML=rows.length?rows.map((p,i)=>`<article class="card project"><div class="project-no">${String(i+1).padStart(2,'0')}</div><span class="tag">${escapeHtml(p.category)}</span><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.description)}</p>${p.contract?`<div class="muted">${short(p.contract)}</div>`:''}${p.website?`<a class="btn small" target="_blank" rel="noopener" href="${escapeHtml(p.website)}">Open ↗</a>`:''}</article>`).join(''):'<div class="empty">NO APPROVED PROJECTS YET.</div>'}catch(e){$('#projects').innerHTML=`<div class="empty">PROJECT DIRECTORY UNAVAILABLE<br><small>${escapeHtml(e.message)}</small></div>`}}
loadProjects();

const modal=$('#modal');function openModal(){modal.classList.add('show');modal.setAttribute('aria-hidden','false');setTimeout(()=>modal.querySelector('input').focus(),50)}function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}$('#submitBtn').onclick=openModal;$('#close').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$('#projectForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const data=Object.fromEntries(new FormData(e.target));await api('/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});e.target.reset();closeModal();toast('Project submitted for admin review.');}catch(err){toast(err.message,false)}finally{btn.disabled=false}};

$('#menu').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));
