const CHAIN={id:'0x1237',decimal:4663,name:'Robinhood Chain',rpc:'https://rpc.mainnet.chain.robinhood.com',explorer:'https://robinhoodchain.blockscout.com'};
const $=id=>document.getElementById(id);
const fallback=[['WETH','Wrapped Ether','$—','LIVE'],['USDG','USDG','$—','LIVE'],['RWA','RWA INDEX','$—','DEMO']];
function short(a){return a?`${a.slice(0,6)}…${a.slice(-4)}`:''}
async function api(url,opts){const r=await fetch(url,opts);const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}
function setFeed(lines){$('terminalFeed').innerHTML=lines.map((x,i)=>`<div>[${String(i+1).padStart(2,'0')}] ${x}</div>`).join('')}
setFeed(['BOOT > RH//HUB initializing...','CHAIN > Robinhood Chain / 4663','RPC > connecting to mainnet...','INDEX > preparing live reads...','SECURITY > read-only mode','READY > command center online']);
async function loadChain(){try{const c=await api('/api/chain');$('chainBlock').textContent=c.blockNumber.toLocaleString();$('gasValue').textContent=(Number(BigInt(c.gasWei))/1e9).toFixed(3)+' GWEI';$('networkState').textContent='● ONLINE';$('networkState').className='up';setFeed([`RPC > ${c.client||'EVM node'} online`,`BLOCK > #${c.blockNumber.toLocaleString()}`,`GAS > ${(Number(BigInt(c.gasWei))/1e9).toFixed(3)} gwei`,'CHAIN > ID 4663 confirmed','INDEX > live RPC reads active','READY > command center online'])}catch(e){$('networkState').textContent='● RPC ERROR';$('networkState').className='red'}}
function renderTokens(){const rows=[...fallback];$('tokenList').innerHTML=rows.map(t=>`<div class="token"><div class="pixel-icon">${t[0][0]}</div><div><b>${t[1]}</b><small>Robinhood Chain</small></div><div>${t[2]}</div><div class="green">${t[3]}</div><a class="btn" target="_blank" href="${CHAIN.explorer}">VIEW ↗</a></div>`).join('')}
async function connect(){if(!window.ethereum){alert('Install an EVM wallet such as MetaMask or Robinhood Wallet.');return}try{await window.ethereum.request({method:'eth_requestAccounts'});const cid=await window.ethereum.request({method:'eth_chainId'});if(cid.toLowerCase()!==CHAIN.id){try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:CHAIN.id}]})}catch(e){if(e.code===4902)await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:CHAIN.id,chainName:CHAIN.name,nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:[CHAIN.rpc],blockExplorerUrls:[CHAIN.explorer]}]});else throw e}}const accounts=await window.ethereum.request({method:'eth_accounts'});const a=accounts[0];$('connectBtn').textContent=short(a);$('portfolioConnect').textContent='CONNECTED';$('walletAddress').textContent=short(a);await loadWallet(a)}catch(e){alert(e.message||'Wallet connection failed')}}
async function loadWallet(a){try{const d=await api('/api/address/'+a);$('balance').textContent=(Number(BigInt(d.balanceWei))/1e18).toFixed(4)+' ETH';$('walletMeta').textContent=d.isContract?'CONTRACT ADDRESS':'EOA WALLET';}catch(e){$('balance').textContent='READ ERROR'}}
$('connectBtn').onclick=connect;$('portfolioConnect').onclick=connect;
$('scanBtn').onclick=async()=>{const a=$('addressInput').value.trim();if(!/^0x[a-fA-F0-9]{40}$/.test(a)){ $('scanResult').innerHTML='<div class="result-empty">INVALID ADDRESS<br><span>USE A 42-CHARACTER EVM ADDRESS</span></div>';return}try{const d=await api('/api/address/'+a);let token={};if(d.isContract)token=await api('/api/token/'+a);$('scanResult').innerHTML=`<div class="eyebrow">LIVE RPC SCAN // READ-ONLY</div><div class="risk">${d.isContract?'CONTRACT FOUND':'EOA WALLET'}</div>${[['TYPE',d.isContract?'SMART CONTRACT':'EXTERNALLY OWNED ACCOUNT'],['BYTECODE',`${d.codeBytes} bytes`],['ETH BALANCE',(Number(BigInt(d.balanceWei))/1e18).toFixed(6)],['NONCE / TX COUNT',d.nonce],['TOKEN NAME',token.name||'—'],['TOKEN SYMBOL',token.symbol||'—'],['DECIMALS',token.decimals?parseInt(token.decimals,16):'—']].map(x=>`<div class="check"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<a class="btn" style="margin-top:18px" target="_blank" href="${d.blockscout}">OPEN BLOCKSCOUT ↗</a>`}catch(e){$('scanResult').innerHTML=`<div class="result-empty">RPC ERROR<br><span>${e.message}</span></div>`}};
$('addressInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('scanBtn').click()});
const projectsFallback=[['01','PIXEL RWA','RWA','Tokenized asset discovery & analytics.'],['02','CHAINLABS','TOOL','Developer tools for RH Chain.'],['03','ROBIN ART','NFT','Community digital collectibles.']];
async function loadProjects(){let ps;try{ps=await api('/api/projects')}catch{ps=[]}const data=ps.length?ps.map((p,i)=>[String(i+1).padStart(2,'0'),p.name,p.category,p.description]):projectsFallback;$('projectGrid').innerHTML=data.map(p=>`<article class="project"><div class="pixel-icon">${p[0]}</div><span class="tag">${p[2]}</span><h3>${p[1]}</h3><p>${p[3]}</p><span class="tag">APPROVED</span></article>`).join('')}
const modal=$('projectModal');function openModal(){modal.classList.add('show')}function closeModal(){modal.classList.remove('show')}$('submitProject').onclick=openModal;$('submitProject2').onclick=openModal;$('closeModal').onclick=closeModal;window.onclick=e=>{if(e.target===modal)closeModal()};$('projectForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:f.get('name'),address:f.get('address'),category:f.get('category'),link:f.get('link'),description:f.get('description')})});alert('PROJECT SUBMITTED FOR ADMIN REVIEW.');e.target.reset();closeModal()}catch(err){alert(err.message)}};
$('ticker').innerHTML=' LIVE RPC ◆ CHAIN 4663 ◆ ETH GAS ◆ EVM COMPATIBLE ◆ PERMISSIONLESS ◆ RWA NATIVE ◆ LIVE RPC ◆ CHAIN 4663 ◆ ETH GAS ◆ EVM COMPATIBLE ◆';
$('chainBlock').textContent='—';$('gasValue').textContent='—';$('networkState').textContent='● CONNECTING';$('walletAddress').textContent='NOT CONNECTED';
renderTokens();loadProjects();loadChain();setInterval(loadChain,15000);
