-- Rhoodstone Mission v3: wallet identity + campaign management.
create extension if not exists pgcrypto;
create table if not exists public.wallet_profiles(id uuid primary key default gen_random_uuid(), wallet_address text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.projects(id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text, logo_url text, starts_at timestamptz not null, ends_at timestamptz not null, gtd_slots integer not null default 0 check(gtd_slots>=0), status text not null default 'draft' check(status in('draft','scheduled','live','ended')), created_at timestamptz not null default now(), check(ends_at=starts_at+interval '24 hours'));
create table if not exists public.mission_tasks(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,title text not null,task_type text not null check(task_type in('x_follow','x_like','x_repost','website','discord','custom')),target_value text,required boolean not null default true,sort_order integer not null default 0);
create table if not exists public.mission_submissions(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,wallet_address text not null,stake_balance_at_submit numeric not null default 0,status text not null default 'verified' check(status in('pending','verified','rejected')),submitted_at timestamptz not null default now(),verified_at timestamptz,unique(project_id,wallet_address));
create table if not exists public.task_verifications(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,task_id uuid not null references public.mission_tasks(id) on delete cascade,wallet_address text not null,status text not null check(status in('verified','failed','pending')),checked_at timestamptz not null default now(),source text not null default 'server',unique(project_id,task_id,wallet_address));
create table if not exists public.gtd_winners(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,wallet_address text not null,selected_at timestamptz not null default now(),draw_id uuid,unique(project_id,wallet_address));
alter table public.projects enable row level security; alter table public.mission_tasks enable row level security; alter table public.mission_submissions enable row level security; alter table public.gtd_winners enable row level security;
create policy "public visible projects" on public.projects for select using(status in('scheduled','live','ended'));
create policy "public visible tasks" on public.mission_tasks for select using(exists(select 1 from public.projects p where p.id=project_id and p.status in('scheduled','live','ended')));
-- Do NOT allow anonymous clients to insert submissions directly in production. Use the Edge Function with service-role credentials.
create policy "public winners after end" on public.gtd_winners for select using(exists(select 1 from public.projects p where p.id=project_id and p.status='ended'));
