// Supabase Edge Function: authenticated wallet-signed mission submission.
// Deploy as `submit-mission`. Set SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY and RPC_URL secrets.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { ethers } from 'https://esm.sh/ethers@6.15.0';
const STAKING='0xA1Cf1e04c74984F7aF8CCd79Fb17E4fee54302E7';
const ABI=['function isOGEligible(address) view returns (bool)','function stakedBalance(address) view returns (uint256)'];
const rpc=Deno.env.get('RPC_URL')||'https://rpc.mainnet.chain.robinhood.com';
const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
Deno.serve(async req=>{try{if(req.method!=='POST')return json({error:'POST only'},405);const body=await req.json();const {project_id,wallet_address,message,signature}=body;if(!project_id||!wallet_address||!message||!signature)return json({error:'project_id, wallet_address, message and signature are required'},400);const recovered=ethers.verifyMessage(message,signature);if(recovered.toLowerCase()!==wallet_address.toLowerCase())return json({error:'Wallet signature does not match address'},401);if(!message.includes(wallet_address.toLowerCase()))return json({error:'Invalid signing message'},400);const {data:p,error:pe}=await supabase.from('projects').select('*').eq('id',project_id).single();if(pe||!p)return json({error:'Project not found'},404);const now=Date.now();if(p.status!=='live' || now<new Date(p.starts_at).getTime() || now>=new Date(p.ends_at).getTime())return json({error:'Campaign is not live'},400);const provider=new ethers.JsonRpcProvider(rpc);const c=new ethers.Contract(STAKING,ABI,provider);const [eligible,balance]=await Promise.all([c.isOGEligible(wallet_address),c.stakedBalance(wallet_address)]);if(!eligible||balance<=0n)return json({error:'Active Rhood Stone stake required'},403);const {data:tasks,error:te}=await supabase.from('mission_tasks').select('id,required').eq('project_id',project_id);if(te)return json({error:te.message},500);const required=(tasks||[]).filter(t=>t.required);const {data:ver,error:ve}=await supabase.from('task_verifications').select('task_id,status').eq('project_id',project_id).eq('wallet_address',wallet_address.toLowerCase()).eq('status','verified');if(ve)return json({error:ve.message},500);const verified=new Set((ver||[]).map(x=>x.task_id));const missing=required.filter(t=>!verified.has(t.id)).map(t=>t.id);if(missing.length)return json({error:'Required tasks are not verified yet',missing_task_ids:missing},400);const {data:existing}=await supabase.from('mission_submissions').select('id').eq('project_id',project_id).eq('wallet_address',wallet_address.toLowerCase()).maybeSingle();if(existing)return json({error:'Already submitted'},409);const {data:sub,error:se}=await supabase.from('mission_submissions').insert({project_id,wallet_address:wallet_address.toLowerCase(),stake_balance_at_submit:balance.toString(),status:'verified',verified_at:new Date().toISOString()}).select().single();if(se)return json({error:se.message},500);return json({ok:true,submission:sub});}catch(e){return json({error:e?.message||'Server error'},500)}});
function json(x,status=200){return new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json','access-control-allow-origin':'*'}})}
